### ISSUE TITLE
Testing roadmap

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#141]
ATM we have the API tested on server side. We have to additionally:

- [x] Check the server for some missing unit tests where it makes sense (e.g. mails, ...)
- [x] Add Frontend e2e tests
  - [x] Login / Logout
  - [x] Cookies
  - [x] Navigate to boulder
  - [x] Create crag
  - [x] Create sector
  - [x] Create area
  - [x] Create line
  - [x] Create topo image
  - [x] Draw line on topo image
- [x] Add Frontend unit tests where it makes sense
- [x] Add frontend unit tests in CI
- [x] Add backend unit tests in CI
- [x] Add e2e tests in CI
- [x] Add CI actions as PR condition and run on PRs only and disallow push on main branch
