### ISSUE TITLE
Gym usage

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#341]
- [x] Gym Mode instance setting #485 
- [x] Add "old" Property to lines and Topo images #480 
- [x] Add a "reset" action to set an area old #480
- [x] Old items are not shown in area by default #480
- [ ] Additional ranking that is restricted to the last X weeks
- [ ] Boulder add workflow that makes it super fast to add new lines
- [x] Possibility to add custom gym grading scales
- [x] Add new translation that translates words like e.g. "Crag" to "Gym"
- [x] Different colors for lines #487 
- [x] Optionally remove a level of regional hierarchy #492 
- [ ] Topo image pagination

**Comment by dorthrithil** [comment]
@PeterGrabowitz  any additional ideas?

**Comment by BlobbyBob** [comment]
Additional features:
- [ ] Different colors for lines
- [ ] Optionally remove a level of regional hierarchy (related to #97)

**Comment by dorthrithil** [comment]
- [ ] Topo image pagination (relevant after longer gym mode usage when viewing the topo images with archived lines)

**Comment by dorthrithil** [comment]
Created new issues for the remaining tasks
